### ISSUE TITLE
closing help

### ISSUE THREAD

**Issue by spiderbit** [xahlee/xah-fly-keys#10]
I am not shure if thats a question or a issue but I seek a solution :)

the problem is when I have 2 frames open and I open the help menu on one of it, it uses the other frame to show the help buffer, so far so good normaly I would press q to quit-window and I would been back to the previous 2 buffers open in the 2 frames.

now q is shadowed by a copy command. the closest thing to quit-window I found is Menu t h which is bound to (xah-close-current-buffer), but then it dont open the last opened buffer in this frame, at least not always.

Do you use some config that opens the help menu always in a new frame or what am I missing? Do you never use the help menu? :)

I know I could modespecific bind q again to keyboard-quit but then I would loose the ability to copy text from help so I think thats no good solution, too.

I just noticed that this behaviour of not showing the last buffer only occurs when the old buffer was a jabber-chat-buffer.

But quit-window works also if the "overlapped" buffer was jabber-chat. So I guess I at least understand how it should be used, so that its not working with jabber-chat seems to be really a bug.

**Comment by xahlee** [comment]
how do you use the help menu to show its content to the another frame?

but anyway

if you look at the end of
xah-close-current-buffer
it has code to make sure the buffer shown is a user buffer. I think what happened is that the jabber-chat buffer isn't user buffer. (i.e. its buffer name starts with *)

i think you could try simply to remove that part of code and see how you like it.

Or, figure out exactly how buffers are ordered, and modify the code used in
xah-close-current-buffer and
xah-next-user-buffer and
xah-previous-user-buffer.

right now they just keep calling next-buffer. The issue is that next-buffer is a high-level command. I am pretty sure there's a more efficient lower level code to switch to next buffer, but i haven't looked into.

the problem of closing a window and the next buffer does not show exactly what i expected sometimes happens to me too, especially just closing a image file. My work around is simply to press f11 or f12 to
xah-next-user-buffer <C-next>, <C-tab>, <f12>.
or
xah-previous-user-buffer <C-prior>, <C-S-iso-lefttab>, <f11>.
to switch to the buffer i want.

lastly, if you have a easy thumb key to toggle xah-fly-keys, let's call it X, then, you can just do X q X. (are you still on Truly ergonomic keyboard. i forgot if you also had kinesis...)

**Comment by xahlee** [comment]
another solution is to add a option to determine what constitutes a “user” buffer and “emacs” buffer. Right now they are simply determined by whether the buffer name starts with *.

this might be a good solution so that people can add special buffers to be considered as user buffer.

do you think this is something useful?

**Comment by spiderbit** [comment]
I yesterday updated to the newer version that solved some issues and added some, this was one of am and I thought its to basic I cant complain if you dont use gnus and I have to do modespecific stuff but the help screen is pretty basic.

I dont know if I can accept using Menu t h instead of only q, but for now it would be good enough.

I have some other points I dont really get, as example I get why q is shadowed in command mode, but has it be shadowed in insert mode? in insert mode either if its a writable buffer would normaly type the letter or in this case of a readonly buffer could do the mode specific action.

I am also confused why you switched around q and j for copying and cutting but I will get used to it.
and yes the buffername starts with *.

I still use the TECK, the help menu is shown in another window I think (I mix up always the term window and frame, I think thats default behaviour?)

but yes deactivating fly keys from time to time could help, even it got better with magit it still shadows many keys, and I dont have to much interest to config it somehow with mode specific stuff.

another funny thing is, that I use for many modes german prefix, then a o e keys dont reakt because it waits till I press the 2nd letter to gerate the german umlauts, that makes sense in insert mode not so much in command mode I think.

have to try some of your suggestions and come back to it.

**Comment by xahlee** [comment]
just updated. Now when insert mode, they should fall into whatever the major mode's keys. e.g. in dired, put to insert mode, then d will call dired-flag-file-deletion.

**Comment by xahlee** [comment]
for the swap of copy/paste keys. The reason is that cut is much more frequent then copy. And middle finger pressing a key below homerow is butter than the ring finger. The disadvantage is that it just swapped tradition, so a throwback. i figured since xfk is totally new, might as well go with the more efficient route.

**Comment by xahlee** [comment]
@spiderbit did you try it?

**Comment by spiderbit** [comment]
"just updated. Now when insert mode, they should fall into whatever the major mode's keys. that is, q will work now for burying help buffer."

sry did miss that, I did not update to the newest version I use the melpa version at the moment, you most likely dont update that so often?

But sounds good, maybe I switch back to the git version. sounds good. At the moment I use menu end to quit fly keys in the modes/situations I need it, it works ok, this patch would make it better so I think I can live with it :)

another alternitiv would be to modespecific deactivate with a hook fly-keys.

thx :)

**Comment by spiderbit** [comment]
ok just saw that its already in the melpa version. after evaling the new file/version, I can quit the help with q.

seems a nice improvement.

**Comment by spiderbit** [comment]
hmm next logical step would be a list where it should start with command mode and where with insert mode, but I think thats more configuration issue with hooks not something you need to code into fly-keys.

at some modes its more logical or you would more often want the mode specific keys in some you more likely want the command mode. but its good to have both.

But thats more a preference thing I guess, do you copy often stuff from help or do you most of the time only look at it and close it. do you move more in magit your cursor or do you more likely call the commands :)

I think gnus navigation modes I need seldom command mode, more when I start to write a mail in message mode.

but that should be reasonalbe easy to configure now.

**Comment by xahlee** [comment]
@spiderbit  great. Thanks.
git and melpa are synced. Unless author purposefully made it otherwise, else melpa should show updates within a day.

the fall back behavior in insert mode is nice. For me too. Do report if you have issues. Thanks.
