### ISSUE TITLE
Allow yank into minibuffer for isearch?

### ISSUE THREAD

**Issue by pierwill** [xahlee/xah-fly-keys#55]
Is this possible? Or maybe a wrapper to isearch for word at point?

**Comment by xahlee** [comment]
C-y should do. that's emacs default key. 
A minor issue is that it's relying on a emacs default with control. But it seem ok for now unless more people complain. The issue is, if we add keys to isearch, it'd have to be a meta or control combination anyway. It could also be a leader key sequence, but we'll need to create a spot just for it, or, using a existing leader key for paste... maybe this last one is a good way.
